{
    "sealEngine":"PBFT",
    "systemproxyaddress":"${CONFIG_JSON_SYSTEM_CONTRACT_ADDRESS_TPL}",
    "listenip":"${CONFIG_JSON_LISTENIP_TPL}",
    "cryptomod":"${CRYPTO_MODE_TPL}",
    "rpcport":"${CONFIG_JSON_RPC_PORT_TPL}",
    "p2pport":"${CONFIG_JSON_P2P_PORT_TPL}",
    "channelPort":"${CHANNEL_PORT_VALUE_TPL}",
    "wallet":"${CONFIG_JSON_KEYS_INFO_FILE_PATH_TPL}",
    "keystoredir":"${CONFIG_JSON_KEYSTORE_DIR_PATH_TPL}",
    "datadir":"${CONFIG_JSON_FISCO_DATA_DIR_PATH_TPL}",
    "networkid":"12345",
    "logverbosity":"4",
    "coverlog":"OFF",
    "eventlog":"ON",
    "statlog":"ON",
    "logconf":"${CONFIG_JSON_FISCO_LOGCONF_DIR_PATH_TPL}"
}
